name: Synchronize source code

on:
  push:
    branches:
    - main

jobs:
  sync:
    uses: ArnaudTA/actions/.github/workflows/sync.yaml@v1
    secrets:
      GILTAB_PROJECT_NAME: "${{ vars.GILTAB_PROJECT_NAME }}"
      GITLAB_MIRROR_ID: "${{ vars.GITLAB_MIRROR_ID }}"
      GITLAB_TRIGGER_TOKEN: "${{ secrets.GITLAB_TRIGGER_TOKEN }}"
      GITLAB_URL:  "${{ secrets.GITLAB_URL }}"
      GITLAB_TOKEN: "${{ secrets.GITLAB_TOKEN }}"
    with:
      WAIT: true
